import Layer1_Core
import Trinity_HalfStep_Dual_Theorem
import SmallWorld_Overlap_Flip_Theorem
import Diminished_Chord_ZMod12_Theorem
import Chromatic_Breathing_52_Concurrency_Theorem
import Quarter_Cycle_ZMod_Theorem
import Angular_Embedding_Discrete_Quotient_Theorem
import Trinitarian_Kernel_Proxy_Package_Theorem
import Fourier_ZMod_DFT_Translation_Theorem
import Fourier_ZMod_DFT_Convolution_Theorem
import Fourier_ZMod13_Packaging_Theorem
import Spherical_Harmonic_Breathing_Theorem
import Prime13_Depth_Boundary_Theorem
import QuaternionGroup_Octave_Lens_Theorem
import Octonion_Fano_Nonassociative_Witness
import Wallis_Product_Theorem
import Coefficient_Denominator_Emergence_Theorem
import Exact_Cancellation_Theorem
import Exact_Cancellation_Product_Theorem
import Catalan_42_Theorem
import Unity_Cube_Identities
import Interval_Inversion_Ratio_Theorem
import Interface_Polynomial_Identities_Theorem
import Platonic_Pythagorean_Triangle_Theorem
import Noether_Symmetry_Conservation_Lens_Theorem
import Aspect_Projection_Kernel_Theorem
import REST_Seam_AspectProjection_Bridge_Theorem
import REST_Seam_ObserverProjection_Bridge_Theorem
import REST_Seam_Unified_Interface_Theorem
import Composed_Tick_API_Theorem
import Kernel_Observer_Cycle_Stitch_Theorem
import Observer_Digits_CyclePosition_Bridge_Theorem
import Observer_Digits_Cycle_Periodicity_Bridge_Theorem
import Observer_Cycle_Bridge_API_Theorem
import TwinPrime_AllowedCapacity_Theorem
import TwinPrime_AllowedCapacity_CRT_Theorem
import TwinPrime_AllowedCapacity_CRT_List_Theorem
import TwinPrime_AllowedCapacity_PrimePower_Product_Theorem
import TwinPrime_AllowedCapacity_Density_Theorem
import TwinPrime_AllowedCapacity_Density_Wrapper_Theorem
import TwinPrime_AllowedCapacity_Totient_Bridge_Theorem
import TwinPrime_AllowedCapacity_Totient_Bridge_Wrapper_Theorem
import TwinPrime_AllowedCapacity_Totient_Bridge_Examples
import TwinPrime_AllowedCapacity_Wrapper_Examples
import TwinPrime_Architecture_Occupancy_Boundary_Theorem
import TwinPrime_Architecture_Occupancy_ProductBoundary_Theorem
import TwinPrime_Architecture_Occupancy_ProductBoundary_Examples

/-!
# Layer 2: Bridges

Bridge modules that connect core arithmetic closure to named geometric/harmonic
views used across UFRF narratives.
-/
