import Layer0_Kernel
import Recursive_Grid_Generic_Base_Theorem
import Recursive_Grid_CarryCascade_Theorem
import Recursive_Grid_BlockPeriodicity_Theorem
import Recursive_Grid_Base13_Theorem
import Recursive_Grid_Base10_Theorem
import RecursiveGrid_IndexOfIndexes_Bridge_Theorem
import Index_Of_Indexes_Theorem
import Index_Of_Indexes_Subcycle_Fiber_Theorem
import Index_Of_Indexes_Subintervals_Theorem
import REST_Seam_Overlap_Theorem
import REST_Seam_Transport_Core_Theorem
import REST_Seam_Transport_Theorem
import REST_Seam_Classification_Theorem
import Seam_Generic_Classification_Theorem
import REST_Seam_RecursiveGrid_Bridge_Theorem
import Seam_Generic_API_Theorem
import Seam_Generic_NodeClosure_Bridge_Theorem
import REST_Seam_Generic_Canonical_Equiv_Theorem
import NodeClosure_Singleton_Generic_Theorem
import REST_Seam_NodeClosure_Bridge_Theorem
import REST_Seam_SystemCoordMixed_Bridge_Theorem
import Decimal_Mod1001_Concurrency_Theorem
import Gap_Set_Prime_Theorem
import Semigroup_Concurrency_Theorem
import Semigroup_Standard_Semantics_Theorem
import Semigroup_Coefficient_Witness_Theorem
import Semigroup_Unity_One_Theorem
import UFRF_Minimal_Semigroup_Seed_Theorem
import UFRF_Global_Gap_Theorem
import UFRF_Seed_Global_Gap_Theorem
import Seed_Inevitability_GapSignature_Theorem
import Node_Building_Monotonicity_Theorem
import Tzolkin_Identity_Theorem
import Inverse_Constant_Definition_Theorem
import Golden_Silver_Inverse_Identities_Theorem
import SL_Mirror_Involution_REST_Theorem
import Triad_Balance_Definition_Theorem
import Dimensional_Doubling_Sequence_Theorem
import C_Transform_Identity_Theorem
import Multi_Constant_Resonance_Model_Theorem
import SL13_Cardinality_Theorem
import Prime_Self_Perspective_Theorem
import Trinity_Source_4441_Theorem

/-!
# Layer 1: Core

Discrete UFRF core structures:
- recursive index/carry/grid closure,
- semigroup standard semantics and gap logic,
- decimal/mod1001 concurrency,
- node-building monotonicity.
-/
